name: Build

on: push

jobs:
  run-build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build project
        run: yarn build